apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- name: getotp
  newName: quay.io/shailendra14k/getotp
  newTag: "14.0"
